MODEL: Gemini
OPENAI_API_BASE: https://api.openai.com/v1/chat/completions
OPENAI_API_KEY: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
OPENAI_API_MODEL: gpt-4o
MAX_TOKENS: 1024
TEMPERATURE: 0.0
REQUEST_INTERVAL: 3

# Gemini Model Settings
GEMINI_API_KEY: "AIzaSyAX5wUhomG8Ew7z5DWrHgauF-uqzTtIKoQ"
GEMINI_MODEL_NAME: "gemini-1.5-flash" # Or your preferred Gemini vision model (e.g., gemini-1.5-pro-latest)

# DASHSCOPE_API_KEY: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# QWEN_MODEL: qwen-vl-max
ANDROID_SCREENSHOT_DIR: /sdcard/
ANDROID_XML_DIR: /sdcard/
DOC_REFINE: true
MAX_ROUNDS: 20
MAX_EXPLORE_ROUNDS: 50
DARK_MODE: false
MIN_DIST: 10 
